
server:
  port: 9001


spring:        
 datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1522/xe
    username: test_user
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
    

    
 thymeleaf:
    prefix: classpath:/templates/   
    suffix: .html  
    cache: false 
    view-names: /*
   
 jpa:
    database: oracle
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    


logging:
  level:
    '[org.hibernaete]': info


    


   
