spring:        
 datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1522/xe
    username: test_user
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
   
 jpa:
    database: oracle
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    


 
server:
    port:
        8082      

logging:
  level:
    '[org.hibernaete]': info
    


   
